variables:
    SolutionBaseName: 'DFC.Api.Lmi.Import'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'SkillsFundingAgency'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

# trigger: 
#   branches:
#     include: 
#     - dev
#     - master

# pr:
#   branches:
#     include: 
#     - dev
#     - master

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'

- stage: DeployToDevApiLmiImport
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  condition: succeeded()
  displayName: Deploy to DEV_ApiLmiImport
  variables:
  - template: VariableTemplates/DevEnvironmentVariables.yml
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-dev
  - group: dfc-app-shared-dev
  #- group: 'KeyVault - dfc-dev-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: DEV_ApiLmiImport
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: LmiImport
            azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmiimport-fa'

- stage: DeployToDevDraftApiLmiImport
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  condition: succeeded()
  displayName: Deploy to DEV-DRAFT_ApiLmiImport
  variables:
  - template: VariableTemplates/DevDraftEnvironmentVariables.yml
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-dev
  - group: dfc-app-shared-dev
  #- group: 'KeyVault - dfc-dev-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: DEV-DRAFT_ApiLmiImport
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: api-LmiImport
            azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmiimport-fa'

- stage: DeployToSitApiLmiImport
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  condition: succeeded()
  displayName: Deploy to SIT_ApiLmiImport
  variables:
  - template: VariableTemplates/SitEnvironmentVariables.yml
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-sit
  - group: dfc-app-shared-sit
  #- group: 'KeyVault - dfc-sit-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: SIT_ApiLmiImport
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: api-LmiImport
            azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmiimport-fa'

- stage: DeployToSitDraftApiLmiImport
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  condition: succeeded()
  displayName: Deploy to SIT-DRAFT_ApiLmiImport
  variables:
  - template: VariableTemplates/SitDraftEnvironmentVariables.yml
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-sit
  - group: dfc-app-shared-sit
  #- group: 'KeyVault - dfc-sit-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: SIT-DRAFT_ApiLmiImport
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: api-LmiImport
            azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmiimport-fa'