variables:
    SolutionBaseName: 'DFC.Api.Lmi.Import'
    ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.15.0
    endpoint: 'SkillsFundingAgency'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

trigger: 
  branches:
    include: 
    - dev
    - master

pr:
  branches:
    include: 
    - dev
    - master

stages:
- stage: Build
  jobs:
  - job:
    displayName: Build and test application & templates"
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        PublishWebApp: true
        TestSuffix: UnitTests

- stage: DeployToLabApiLmiImport
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  displayName: Deploy to LAB-ApiLmiImport
  variables:
  - group: dfc-shared-lab
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-lab
  - group: dfc-app-shared-lab
  - group: 'KeyVault - dfc-lab-shared-kv'
  - template: VariableTemplates/LabEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: LAB-ApiLmiImport
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmi-import-fa'

- stage: DeployToDevApiLmiImport
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_ApiLmiImport
  variables:
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-dev
  - group: dfc-app-shared-dev
  - group: 'KeyVault - dfc-dev-shared-kv'
  - template: VariableTemplates/DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV_ApiLmiImport
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmi-import-fa'

- stage: DeployToSitApiLmiImport
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT_ApiLmiImport
  variables:
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-sit
  - group: dfc-app-shared-sit
  - group: 'KeyVault - dfc-sit-shared-kv'
  - template: VariableTemplates/SitEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT_ApiLmiImport
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmi-import-fa'

- stage: DeployToPPApiLmiImport
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to PP_ApiLmiImport
  variables:
  - group: dfc-shared-pp
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-pp
  - group: dfc-app-shared-pp
  - group: 'KeyVault - dfc-pp-shared-kv'
  - template: VariableTemplates/PPEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: PP_ApiLmiImport
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmi-import-fa'

- stage: DeployToPRDApiLmiImport
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to PRD_ApiLmiImport
  variables:
  - group: dfc-shared-prd
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-prd
  - group: dfc-app-shared-prd
  - group: 'KeyVault - dfc-prd-shared-kv'
  - template: VariableTemplates/PRDEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-DIG-Prod (6c93f7dc-6c36-4ea6-8de3-3f4574f88027)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: PRD_ApiLmiImport
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-lmi-import-fa'