variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ReleaseEnvironmentName
  value: dev-draft
- name: WebAppPrefix
  value: dfc-dev-draft
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-lmi-import-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-lmi-import-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-lmi-import-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-lmi-import-asp
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Import-draft
- name: LmiImportTimerTriggerSchedule
  value: 0 0 4 1 * *
- name: ApiSuffix
  value: (draft)
- name: Neo4jEndpoints0Name
  value: Draft
- name: Neo4jEndpoints0Uri
  value: $(Neo4jUrl)
- name: Neo4jEndpoints0Username
  value: $(Neo4jUser)
- name: Neo4jEndpoints0Password
  value: $(Neo4jPassword)
- name: Neo4jReplicaSets0ReplicaSetName
  value: draft
- name: Neo4jReplicaSets0GraphInstances0Endpoint
  value: Draft
- name: Neo4jReplicaSets0GraphInstances0GraphName
  value: draft
- name: GraphOptionsContentApiUriPrefix
  value: https://dfc-dev-draft-api-cont-fa.$(appServiceDomain)/api/execute
- name: GraphOptionsReplicaSetName
  value: draft
- name: JobProfileApiClientOptionsBaseAddress
  value: $(ApimProxyAddress)/job-profiles/summary
- name: JobProfileApiClientOptionsApiKey
  value: $(ApimJobProfilesKey)
- name: EventGridClientOptionsTopicEndpoint
  value: $(EventGridTopicUrl)
- name: EventGridClientOptionsTopicKey
  value: $(EventGridAegSasKey)
- name: EventGridClientOptionsApiEndpointSuffix
  value: https://dfc-dev-draft-api-cont-fa.$(appServiceDomain)/api/execute/lmisoc