variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
<<<<<<< HEAD:Resources/AzureDevOps/VariableTemplates/LabDraftEnvironmentVariables.yml
  value: lab-draft
- name: WebAppPrefix
  value: dfc-lab-draft
=======
  value: lab
- name: WebAppPrefix
  value: dfc-lab
>>>>>>> origin/dev:Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-lmi-import-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-lmi-import-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-lmi-import-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-lmi-import-asp
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Import
- name: LmiImportTimerTriggerSchedule
  value: 0 0 2 1,15 * *
<<<<<<< HEAD:Resources/AzureDevOps/VariableTemplates/LabDraftEnvironmentVariables.yml
- name: ApiSuffix
  value: (draft)
- name: Neo4jEndpoints0Name
  value: Draft
- name: Neo4jEndpoints0Uri
  value: $(Neo4jUrl)
- name: Neo4jEndpoints1Uri
  value: $(Neo4jUrlDraft)
- name: Neo4jEndpoints0Username
  value: $(Neo4jUserDraft)
- name: Neo4jEndpoints0Password
  value: $(Neo4jPasswordDraft)
- name: GraphOptionsContentApiUriPrefix
  value: https://dfc-lab-draft-api-cont-fa.$(appServiceDomain)/api/execute/
=======
>>>>>>> origin/dev:Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml
- name: JobProfileApiClientOptionsBaseAddress
  value: $(ApimProxyAddress)/job-profiles/summary
- name: JobProfileApiClientOptionsApiKey
  value: $(ApimJobProfilesKey)
- name: EventGridClientOptionsTopicEndpoint
  value: $(EventGridTopicUrl)
- name: EventGridClientOptionsTopicKey
  value: $(EventGridAegSasKey)
- name: EventGridClientOptionsApiEndpoint
<<<<<<< HEAD:Resources/AzureDevOps/VariableTemplates/LabDraftEnvironmentVariables.yml
  value: https://dfc-lab-draft-api-cont-fa.$(appServiceDomain)/api/execute/lmisoc
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/LMI/Import-Draft/lmi/webhook?subscription-key=$(apimLmiKey)
- name: subscriptionUrl
  value: https://dfc-lab-api-eventgridsubscriptions-fa.$(FunctionAppDomain)/api/execute/
- name: SubscriptionPosturi
  value: https://$(FunctionAppName).$(FunctionAppDomain)/subscription/
=======
  value: https://dfc-lab-api-lmi-import-fa.$(appServiceDomain)/api/lmi-for-all-data
- name: cosmosCollectionName
  value: lmi-for-all-data
- name: CosmosDbDatabaseThroughput
  value: 1200
>>>>>>> origin/dev:Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml
