variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: lab
- name: WebAppPrefix
  value: dfc-lab
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-lmi-import-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-lmi-import-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-lmi-import-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-lmi-import-asp
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Import
- name: LmiImportTimerTriggerSchedule
  value: 0 0 2 1,15 * *
- name: ApiSuffix
  value:
- name: Neo4jEndpoints0Name
  value: Published
- name: Neo4jEndpoints0Uri
  value: $(Neo4jUrl)
- name: Neo4jEndpoints1Uri
  value: $(Neo4jUrlDraft)
- name: Neo4jEndpoints0Username
  value: $(Neo4jUser)
- name: Neo4jEndpoints0Password
  value: $(Neo4jPassword)
- name: GraphOptionsContentApiUriPrefix
  value: https://dfc-lab-api-cont-fa.$(appServiceDomain)/api/execute/
- name: JobProfileApiClientOptionsBaseAddress
  value: $(ApimProxyAddress)/job-profiles/summary
- name: JobProfileApiClientOptionsApiKey
  value: $(ApimJobProfilesKey)
- name: EventGridClientOptionsTopicEndpoint
  value: $(EventGridTopicUrl)
- name: EventGridClientOptionsTopicKey
  value: $(EventGridAegSasKey)
- name: EventGridClientOptionsApiEndpoint
  value: https://dfc-lab-api-cont-fa.$(appServiceDomain)/api/execute/lmisoc
- name: SubscriptionSettingsEndpoint
  value: ''
- name: subscriptionUrl
  value: ''
- name: SubscriptionPosturi
  value: ''
- name: CosmosDbCollectionName
  value: lmi-for-all-data