variables:
- name: aspTier
  value: Standard
- name: aspInstances
  value: 3
- name: aspSize
  value: 1
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: prd-draft
- name: WebAppPrefix
  value: dfc-prd-draft
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-lmi-import-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-lmi-import-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-lmi-import-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-lmi-import-asp
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Import-draft
- name: LmiImportTimerTriggerSchedule
  value: 0 0 4 1 * *
- name: ApiSuffix
  value: (draft)
- name: Neo4jEndpoints0Name
  value: Draft
- name: Neo4jEndpoints0Uri
  value: $(Neo4jUrlDraft)
- name: Neo4jEndpoints0Username
  value: $(Neo4jUserDraft)
- name: Neo4jEndpoints0Password
  value: $(Neo4jPasswordDraft)
- name: Neo4jReplicaSets0ReplicaSetName
  value: draft
- name: Neo4jReplicaSets0GraphInstances0Endpoint
  value: Draft
- name: Neo4jReplicaSets0GraphInstances0GraphName
  value: draft
- name: GraphOptionsContentApiUriPrefix
  value: https://dfc-prd-draft-api-cont-fa.$(appServiceDomain)/api/execute/
- name: GraphOptionsReplicaSetName
  value: draft
- name: JobProfileApiClientOptionsBaseAddress
  value: $(ApimProxyAddress)/job-profiles/summary
- name: JobProfileApiClientOptionsApiKey
  value: $(ApimJobProfilesKey)
- name: EventGridClientOptionsTopicEndpoint
  value: $(EventGridTopicUrl)
- name: EventGridClientOptionsTopicKey
  value: $(EventGridAegSasKey)
- name: EventGridClientOptionsApiEndpoint
  value: https://dfc-prd-draft-api-cont-fa.$(appServiceDomain)/api/execute/lmisoc