variables:
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 1
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: prd
- name: WebAppPrefix
  value: dfc-prd
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-lmi-import-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-lmi-import-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-lmi-import-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-lmi-import-asp
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Import
- name: LmiImportTimerTriggerSchedule
  value: 0 0 2 1,15 * *
- name: JobProfileApiClientOptionsBaseAddress
  value: $(ApimProxyAddress)/job-profiles/summary
- name: JobProfileApiClientOptionsApiKey
  value: $(ApimJobProfilesKey)
- name: EventGridClientOptionsTopicEndpoint
  value: $(EventGridTopicUrl)
- name: EventGridClientOptionsTopicKey
  value: $(EventGridAegSasKey)
- name: EventGridClientOptionsApiEndpoint
  value: https://dfc-prd-api-lmi-import-fa.$(appServiceDomain)/api/lmi-for-all-data
- name: cosmosCollectionName
  value: lmi-for-all-data
- name: CosmosDbDatabaseThroughput
  value: 400