variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ReleaseEnvironmentName
  value: sit
- name: WebAppPrefix
  value: dfc-sit
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-lmiimport-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-lmiimport-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-lmiimport-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-lmiimport-asp
- name: LmiImportTimerTriggerSchedule
  value: 0 0 1 1 * *
- name: ApiSuffix
  value:
- name: Neo4jEndpoints0Name
  value: Published
- name: Neo4jEndpoints0Uri
  value: $(Neo4jUrl)
- name: Neo4jEndpoints0Username
  value: $(Neo4jUser)
- name: Neo4jEndpoints0Password
  value: $(Neo4jPassword)
- name: Neo4jReplicaSets0ReplicaSetName
  value: published
- name: Neo4jReplicaSets0GraphInstances0Endpoint
  value: Published
- name: Neo4jReplicaSets0GraphInstances0GraphName
  value: published
- name: GraphOptionsContentApiUriPrefix
  value: https://dfc-sit-api-cont-fa.$(appServiceDomain)/api/execute
- name: GraphOptionsReplicaSetName
  value: published
#- name: JobProfileApiClientOptionsBaseAddress
#  value: $(ApimProxyAddress)/job-profiles/summary
- name: JobProfileApiClientOptionsBaseAddress
  value: https://pp.api.nationalcareers.service.gov.uk/job-profiles/summary
- name: JobProfileApiClientOptionsApiKey
  value: $(ApimJobProfilesKey)
- name: EventGridClientOptionsTopicEndpoint
  value: $(EventGridTopicUrl)
- name: EventGridClientOptionsTopicKey
  value: $(EventGridAegSasKey)
- name: ApiEventGridClientOptionsApiEndpointSuffix
  value: $(ContentApiAddress)/api/execute/lmisoc
- name: SubscriptionPosturi
  value: https://dfc-sit-api-appRegistry-fa.$(appServiceDomain)/subscription/